**************************

servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  - http:
      # 是否关闭正向HTTP服务器
      disabled: false
      # 服务端监听地址，用来收QQ信息，可自己设置其它地址
      host: 127.0.0.1
      # 服务端监听端口，用来收QQ信息，可自己设置其它端口
      port: 5700
      # 反向HTTP超时时间, 单位秒
      # 最小值为5，小于5将会忽略本项设置
      timeout: 5
      middlewares:
        <<: *default # 引用默认中间件
      # 反向HTTP POST地址列表
      post:
        - url: 'http://127.0.0.1:8001' # 这个url用来发送信息，可自己设置其它地址
          secret: ''


          ********************